# Generated by Django 2.2.10 on 2025-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(help_text='Masukkan 16 digit NIK dari KK/KTP (wajib dan unik)', max_length=16, unique=True, verbose_name='NIK (16 Digit)')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(max_length=50, verbose_name='Agama')),
                ('alamat', models.TextField(verbose_name='Alamat Lengkap')),
                ('asal_sekolah', models.CharField(max_length=200, verbose_name='Asal Sekolah')),
                ('nama_ayah', models.CharField(blank=True, max_length=200, verbose_name='Nama Ayah Kandung')),
                ('nama_ibu', models.CharField(max_length=200, verbose_name='Nama Ibu Kandung')),
                ('no_wa', models.CharField(help_text='Nomor WhatsApp yang bisa dihubungi', max_length=15, verbose_name='No WA Aktif')),
                ('jurusan', models.CharField(choices=[('TKRO', 'Teknik Kendaraan Ringan Otomotif'), ('TSM', 'Teknik Sepeda Motor'), ('AKL', 'Akuntansi dan Keuangan Lembaga'), ('RPL', 'Rekayasa Perangkat Lunak'), ('KUL', 'Kuliner')], max_length=10, verbose_name='Jurusan yang Dipilih')),
                ('jalur', models.CharField(choices=[('KHUSUS', 'Jalur Khusus'), ('UMUM', 'Jalur Umum')], max_length=10, verbose_name='Jalur Pendaftaran')),
                ('status', models.CharField(choices=[('terdaftar', 'Terdaftar'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('daftar_ulang', 'Daftar Ulang')], default='terdaftar', max_length=20, verbose_name='Status Pendaftaran')),
                ('nomor_pendaftaran', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Nomor Pendaftaran')),
                ('tanggal_pendaftaran', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal & Waktu Pendaftaran')),
            ],
            options={
                'verbose_name': 'Pendaftaran Siswa Baru',
                'verbose_name_plural': 'Pendaftaran Siswa Baru',
                'ordering': ['-tanggal_pendaftaran'],
            },
        ),
    ]
