# Generated by Django 2.2.10 on 2025-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20251219_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='jalur',
            field=models.CharField(blank=True, choices=[('KHUSUS', 'Jalur Khusus'), ('UMUM', 'Jalur Umum')], editable=False, help_text='Otomatis terisi berdasarkan tanggal pendaftaran', max_length=10, verbose_name='Jalur Pendaftaran'),
        ),
    ]
