# Generated by Django 2.2.10 on 2025-12-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20251219_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='alamat',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='desa_kelurahan',
            field=models.CharField(default='', max_length=100, verbose_name='Desa/Kelurahan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='dusun',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dusun/Hamlet'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='kabupaten_kota',
            field=models.CharField(default='', max_length=100, verbose_name='Kabupaten/Kota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='kecamatan',
            field=models.CharField(default='', max_length=100, verbose_name='Kecamatan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='rt',
            field=models.CharField(blank=True, help_text='Contoh: 001', max_length=10, verbose_name='RT'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='rw',
            field=models.CharField(blank=True, help_text='Contoh: 002', max_length=10, verbose_name='RW'),
        ),
    ]
