# Generated by Django 2.2.10 on 2025-12-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20251219_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='nominal_pembayaran',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Masukkan nominal yang sudah dibayar (tanpa titik/rupiah)', max_digits=10, verbose_name='Nominal Pembayaran (Rp)'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tanggal_pembayaran',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pembayaran'),
        ),
    ]
