# Generated by Django 2.2.10 on 2026-01-02 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_logaktivitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='nik',
            field=models.CharField(help_text='Masukkan 16 digit NIK dari KK/KTP (wajib dan unik)', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus terdiri dari 16 digit angka', regex='^\\d{16}$')], verbose_name='NIK (16 Digit)'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='no_wa',
            field=models.CharField(help_text='Contoh: 08xxxxxxxxxx', max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus diawali 08 dan berisi 10–13 digit', regex='^08\\d{8,11}$')], verbose_name='No WA Aktif'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nominal_pembayaran',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Nominal Pembayaran (Rp)'),
        ),
    ]
