# Generated by Django 2.2.10 on 2026-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20260102_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='dusun',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dusun/Dukuh'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='jalur',
            field=models.CharField(blank=True, choices=[('KHUSUS', 'Jalur Khusus'), ('UMUM', 'Jalur Umum')], editable=False, max_length=10, verbose_name='Jalur Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_lengkap',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
    ]
