# Generated by Django 2.2.10 on 2026-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20260103_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='keringanan_prestasi',
            field=models.TextField(blank=True, null=True, verbose_name='Keringanan / Prestasi'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nilai_skl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai SKL'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nisn',
            field=models.CharField(blank=True, max_length=20, verbose_name='NISN'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pekerjaan_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ayah'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pekerjaan_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ibu'),
        ),
    ]
