# Generated by Django 2.2.10 on 2026-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20260103_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='keringanan_prestasi',
            field=models.TextField(blank=True, help_text='Isi manual / checklist admin (dipisah koma)', null=True, verbose_name='Keringanan / Prestasi'),
        ),
    ]
