# Generated by Django 2.2.10 on 2026-01-04 04:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20260103_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logaktivitas',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='aksi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='pendaftaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='keringanan_prestasi',
            field=models.TextField(blank=True, null=True, verbose_name='Keringanan / Prestasi'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Ibu Kandung'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nik',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus terdiri dari 16 digit angka', regex='^\\d{16}$')], verbose_name='NIK (16 Digit)'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='no_wa',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus diawali 08 dan berisi 10–13 digit', regex='^08\\d{8,11}$')], verbose_name='No WA Aktif'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='rt',
            field=models.CharField(blank=True, max_length=10, verbose_name='RT'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='rw',
            field=models.CharField(blank=True, max_length=10, verbose_name='RW'),
        ),
    ]
