# Generated by Django 2.2.10 on 2026-01-04 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='agama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='asal_sekolah',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='desa_kelurahan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='dusun',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='jalur',
            field=models.CharField(blank=True, choices=[('KHUSUS', 'Jalur Khusus'), ('UMUM', 'Jalur Umum')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='jurusan',
            field=models.CharField(choices=[('TKRO', 'Teknik Kendaraan Ringan Otomotif'), ('TSM', 'Teknik Sepeda Motor'), ('AKL', 'Akuntansi dan Keuangan Lembaga'), ('RPL', 'Rekayasa Perangkat Lunak'), ('KUL', 'Kuliner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='kabupaten_kota',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='kecamatan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='keringanan_prestasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_lengkap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nik',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus 16 digit angka', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nilai_skl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nisn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='no_wa',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor WA harus diawali 08 dan 10–13 digit', regex='^08\\d{8,11}$')]),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nominal_pembayaran',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='nomor_pendaftaran',
            field=models.CharField(blank=True, editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='pekerjaan_ayah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='pekerjaan_ibu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='rt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='rw',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='status',
            field=models.CharField(choices=[('terdaftar', 'Terdaftar'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('daftar_ulang', 'Daftar Ulang')], default='terdaftar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='tanggal_pembayaran',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='tanggal_pendaftaran',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='tempat_lahir',
            field=models.CharField(max_length=100),
        ),
    ]
