# Generated by Django 2.2.10 on 2026-01-04 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0013_auto_20260104_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='petugas_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_daftar_ulang', to=settings.AUTH_USER_MODEL),
        ),
    ]
