# Generated by Django 2.2.10 on 2026-01-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0014_pendaftaran_petugas_pembayaran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendaftaran',
            options={'ordering': ['-tanggal_pendaftaran']},
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nominal_pembayaran',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='petugas_pembayaran',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='tanggal_pembayaran',
        ),
        migrations.CreateModel(
            name='PembayaranDaftarUlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nominal', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_daftar_ulang', to='backend.Pendaftaran')),
                ('petugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
