# Generated by Django 2.2.10 on 2026-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('TOGGLE_USER_ACTIVE', 'Toggle User Active'), ('UPDATE_USER_ROLE', 'Update User Role'), ('EXPORT_DATA', 'Export Data'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
